name: Update Repo

on:
  schedule:
    - cron: "* 0 * * *"
  push:
    branches:
      - master
  workflow_dispatch:
  repository_dispatch:
    types: [retry_job]

permissions:
  contents: write

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          repository: ${{ github.repository }}
          ref: master
      - name: Checkout gh-pages
        uses: actions/checkout@v3
        with:
          set-safe-directory: ""
          repository: ${{ github.repository }}
          ref: gh-pages
          path: build
      - name: Set up Python 3.10
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"
          cache: "pip"
      - name: Reset build to initial state
        run: |
          cd build
          git branch -m gh-pages old-gh-pages || true
          git checkout --orphan gh-pages
          git rm -rf .
          cd ..
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          sudo apt update
          sudo apt-get install tesseract-ocr
      - name: Run Program
        env:
          TZ: "Asia/Shanghai"
          USTC_PASSPORT_USERNAME: ${{ secrets.USTC_PASSPORT_USERNAME }}
          USTC_PASSPORT_PASSWORD: ${{ secrets.USTC_PASSPORT_PASSWORD }}
        run: |
          python main.py
      - name: Publish to gh-pages
        run: |
          cd build
          touch .nojekyll
          git config user.name "GitHub"
          git config user.email "noreply@github.com"
          git add .
          git commit -m "Update from: ${{ github.sha }}" --allow-empty
          (git push -f origin gh-pages) || true
