name: Update Repo

on:
  schedule:
    - cron: "* 0 * * *"
  push:
    branches:
      - master
  workflow_dispatch:
  repository_dispatch:
    types: [retry_job]
  discussion_comment:
    types: [created, edited, deleted]

permissions:
  contents: write

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          repository: ${{ github.repository }}
          ref: master
      - name: Checkout gh-pages
        uses: actions/checkout@v3
        with:
          set-safe-directory: ""
          repository: ${{ github.repository }}
          ref: gh-pages
          path: build
      - name: Set up Python 3.10
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"
          cache: "pip"
      - name: Reset build to initial state
        run: |
          cd build
          git branch -m gh-pages old-gh-pages || true
          git checkout --orphan gh-pages
          cd ..
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          sudo apt update
          sudo apt-get install tesseract-ocr
      - name: Run Program
        env:
          TZ: "Asia/Shanghai"
          USTC_PASSPORT_USERNAME: ${{ secrets.USTC_PASSPORT_USERNAME }}
          USTC_PASSPORT_PASSWORD: ${{ secrets.USTC_PASSPORT_PASSWORD }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          LOAD_FROM_FILE: ${{ contains(fromJSON('["push","discussion_comment"]'), github.event_name) && 'True' || 'False' }}
        run: |
          python main.py
      - name: Run mkdocs
        run: |
          cp -r ./build/markdown/* ./mkdocs/docs
          cd mkdocs && mkdocs build >> docs/log.txt 2>&1 && cd ..
          cp -r ./mkdocs/site/* ./build
          wget -O minhtml https://github.com/wilsonzlin/minify-html/releases/download/v0.15.0/minhtml-0.15.0-x86_64-unknown-linux-gnu
          chmod +x minhtml
          for file in $(find ./build -type f -name '*.html'); do
            output_file="${file%.html}.min.html"
            ./minhtml --output "$output_file" --keep-closing-tags --minify-css "$file"
            mv "$output_file" "$file"
          done
      - name: Publish to gh-pages
        run: |
          cd build
          touch .nojekyll
          git config user.name "GitHub"
          git config user.email "noreply@github.com"
          git add .
          git commit -m "Update from: ${{ github.sha }}" --allow-empty
          (git push -f origin gh-pages) || true
